### ISSUE TITLE
Is the time span correct in the HTR-United metadata file?

### ISSUE THREAD

**Issue by alix-tz** [Gallicorpora/HTR-imprime-18e-siecle#1]
Hello!

The time span for the dataset is "1699-1700" but since this repo is for print materials from the 18th century, is it possible that you have a typo here?

**Comment by gabays** [comment]
Correction added:

https://github.com/Gallicorpora/HTR-imprime-18e-siecle/blob/c5a29028ed9c97cffb38e7651d35318f6e424325/htr-united.yml#L26-L27
